version: '3.8'

services:
  # PHP Service
  php:
    build:
      context: .              # Build context is current directory
      dockerfile: docker/php/Dockerfile
    container_name: php83_app # Name our container
    volumes:
      - ./src:/var/www   # Mount our source code
    networks:
      - app-network          # Connect to our network
    environment:
      PHP_IDE_CONFIG: serverName=Docker # For Xdebug
    # Make container restart unless stopped manually
    restart: unless-stopped

  # Nginx Service
  nginx:
    image: nginx:latest      # Use official Nginx image
    container_name: nginx_app
    ports:
      - "8080:80"           # Map port 8080 on our PC to 80 in container
    volumes:
      -  ./src/public:/var/www/public  # Mount same source code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx_logs:/var/log/nginx
    depends_on:
      - php                 # Wait for PHP container
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "rooter"
      MYSQL_DATABASE: "channeldb"
      MYSQL_USER: "master"
      MYSQL_PASSWORD: "rooter"
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "rooter"
    ports:
      - "3000:80"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge          # Standard Docker network type
