export     const  deviceOptions = [
    {id:'none',label:'Select a Device'},
    {id:'mobile',label:'Mobile Phone'},
    {id:'laptop',label:'Laptop'},
    {id:'desktop-computer',label:'Desktop Computer'},

  ];

export const laptopOptions = [
{id:"",label:"Select a Value",dflag:true,hflag:true},
{id:"popbrand",label:"-------Popular Brands-------",dflag:true}, 
{id:"Acer",label:"Acer"}, 
{id:"Apple",label:"Apple"}, 
{id:"Asus",label:"Asus"}, 
{id:"Dell",label:"Dell"}, 
{id:"HCL",label:"HCL"}, 
{id:"HP",label:"HP"}, 
{id:"Huawei",label:"Huawei"}, 
{id:"Lava",label:"Lava"}, 
{id:"Lenovo",label:"Lenovo"}, 
{id:"LG",label:"LG"}, 
{id:"MSI",label:"MSI"}, 
{id:"Sony",label:"Sony"}, 
{id:"Vaio",label:"Vaio"}, 
{id:"othrbrand",label:"-------Other Brands-------",dflag:true}, 
{id:"24MC",label:"24MC"}, 
{id:"AGB",label:"AGB"}, 
{id:"Alienware",label:"Alienware"}, 
{id:"Avita",label:"Avita"}, 
{id:"Azom",label:"Azom"}, 
{id:"Champion_Computers",label:"Champion_Computers"}, 
{id:"Corsair",label:"Corsair"}, 
{id:"CyberPowerPC",label:"CyberPowerPC"}, 
{id:"Fujitsu",label:"Fujitsu"}, 
{id:"Gigabyte",label:"Gigabyte"}, 
{id:"Hisense",label:"Hisense"}, 
{id:"Honor",label:"Honor"}, 
{id:"Hyundai",label:"Hyundai"}, 
{id:"iBall",label:"iBall"}, 
{id:"iLife",label:"iLife"}, 
{id:"Infinix",label:"Infinix"}, 
{id:"Jio",label:"Jio"}, 
{id:"Jumper",label:"Jumper"}, 
{id:"MarQ",label:"MarQ"}, 
{id:"Micromax",label:"Micromax"}, 
{id:"Microsoft",label:"Microsoft"}, 
{id:"Motorola",label:"Motorola"}, 
{id:"Nokia",label:"Nokia"}, 
{id:"Notion_Ink",label:"Notion_Ink"}, 
{id:"Panasonic",label:"Panasonic"}, 
{id:"Razer",label:"Razer"}, 
{id:"RDP",label:"RDP"}, 
{id:"Reach",label:"Reach"}, 
{id:"Realme",label:"Realme"}, 
{id:"Redmi",label:"Redmi"}, 
{id:"Sager",label:"Sager"}, 
{id:"Samsung",label:"Samsung"}, 
{id:"Smartron",label:"Smartron"}, 
{id:"TCL",label:"TCL"}, 
{id:"Tecno",label:"Tecno"}, 
{id:"Toshiba",label:"Toshiba"}, 
{id:"Venturer",label:"Venturer"}, 
{id:"Xiaomi",label:"Xiaomi"},
]

export const mobileOptions = [
 {id:"",label:"Select a Value",dflag:true,hflag:true},
 {id:"popmobile",label:"-------Popular Brands-------",dflag:true}, 
 {id:"Apple",label:"Apple"}, 
 {id:"Asus",label:"Asus"}, 
 {id:"Google",label:"Google"}, 
 {id:"Huawei",label:"Huawei"}, 
 {id:"Lenovo",label:"Lenovo"}, 
 {id:"LG",label:"LG"}, 
 {id:"Micromax",label:"Micromax"}, 
 {id:"Motorola",label:"Motorola"}, 
 {id:"Nokia",label:"Nokia"}, 
 {id:"OnePlus",label:"OnePlus"}, 
 {id:"Oppo",label:"Oppo"}, 
 {id:"Poco",label:"Poco"}, 
 {id:"Realme",label:"Realme"}, 
 {id:"Redmi",label:"Redmi"}, 
 {id:"Reliance",label:"Reliance"}, 
 {id:"Samsung",label:"Samsung"}, 
 {id:"Vivo",label:"Vivo"}, 
 {id:"Xiaomi",label:"Xiaomi"}, 
 {id:"othmobile",label:"-------Other Brands-------",dflag:true}, 
 {id:"AI_Plus",label:"AI_Plus"}, 
 {id:"Alcatel",label:"Alcatel"}, 
 {id:"Black_Shark",label:"Black_Shark"}, 
 {id:"Celkon",label:"Celkon"}, 
 {id:"Coolpad",label:"Coolpad"}, 
 {id:"Gionee",label:"Gionee"}, 
 {id:"Honor",label:"Honor"}, 
 {id:"HTC",label:"HTC"}, 
 {id:"i_Ball",label:"i_Ball"}, 
 {id:"Infinix",label:"Infinix"}, 
 {id:"Infocus",label:"Infocus"}, 
 {id:"Intex",label:"Intex"}, 
 {id:"iQOO",label:"iQOO"}, 
 {id:"Karbonn",label:"Karbonn"}, 
 {id:"Lava",label:"Lava"}, 
 {id:"LYF",label:"LYF"}, 
 {id:"Nothing",label:"Nothing"}, 
 {id:"Panasonic",label:"Panasonic"}, 
 {id:"Spice",label:"Spice"}, 
 {id:"Swipe",label:"Swipe"}, 
 {id:"Tecno",label:"Tecno"}, 
 {id:"Transsion_Group",label:"Transsion_Group"}, 
 {id:"Xolo",label:"Xolo"}, 
 {id:"YU",label:"YU"}
]



export const compOptions = [
    {id:"",label:"Select a Value",dflag:true},
    {id:"Dell",label:"Dell"},
    {id:"HP",label:"HP"},
    {id:"HCL",label:"HCL"},
    {id:"Custom",label:"Custom PC Build"}

]